FROM registry.redhat.io/ubi8:8.4-209 AS builder

RUN INSTALL_PKGS=" \
      rust-toolset \
      cmake \
      make \
      git \
      openssl-devel \
      llvm-toolset \
      cyrus-sasl \
      python36 \
      llvm \
      cyrus-sasl-devel \
      libtool \
      " && \
    yum install -y $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    yum clean all

RUN mkdir -p /tmp/src

WORKDIR /tmp/src
COPY . /tmp/src
USER 0
