[build]
rustflags = [
  "-Dclippy::print_stdout",
  "-Dclippy::print_stderr",
  "-Dclippy::dbg_macro",
]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-rdynamic"]


# for these musl targets libstdc++ will be linked statically (that's configured in e.g. leveldb-sys)
# we provide the location of that library here
[target.x86_64-unknown-linux-musl]
rustflags = "-Lnative=/usr/local/x86_64-linux-musl/lib"

[target.i686-unknown-linux-musl]
rustflags = "-Lnative=/usr/local/i686-linux-musl/lib"

[target.aarch64-unknown-linux-musl]
rustflags = "-Lnative=/usr/local/aarch64-linux-musl/lib"

[target.armv7-unknown-linux-musleabihf]
rustflags = "-Lnative=/usr/local/arm-linux-musleabihf/lib"

[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/Azure/azure-sdk-for-rust.git"]
git = "https://github.com/Azure/azure-sdk-for-rust.git"
rev = "3ca5610b959b3b6b77bb88da09f0764b605b01bc"
replace-with = "vendored-sources"

[source."https://github.com/tokio-rs/tracing"]
git = "https://github.com/tokio-rs/tracing"
rev = "f470db1b0354b368f62f9ee4d763595d16373231"
replace-with = "vendored-sources"

[source."https://github.com/vectordotdev/chrono.git"]
git = "https://github.com/vectordotdev/chrono.git"
branch = "no-default-time"
replace-with = "vendored-sources"

[source."https://github.com/vectordotdev/heim.git"]
git = "https://github.com/vectordotdev/heim.git"
branch = "update-nix"
replace-with = "vendored-sources"

[source."https://github.com/vectordotdev/leveldb-sys.git"]
git = "https://github.com/vectordotdev/leveldb-sys.git"
branch = "leveldb_mmap_limit"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

